import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[radial-gradient(circle_at_20%_20%,#93c5fd33,transparent_35%),radial-gradient(circle_at_80%_0%,#6366f133,transparent_35%),linear-gradient(120deg,#eef2ff,#eff6ff)]`}
      >
        {children}
      </body>
    </html>
  );
}
